jog_arm_server:
  simu: false # Whether the robot is started in simulation environment
  coll_check: false # Check collisions?
  cmd_in_topic:  jog_arm_server/delta_jog_cmds
  cmd_frame:  temoto_end_effector  # TF frame that incoming cmds are given in
  incoming_cmd_timeout:  2.5  # Stop jogging if X seconds elapse without a new cmd
  joint_topic:  hebiros/herbie/command/joint_state
  move_group_name:  manipulator
  singularity_threshold:  6  # Slow down when the condition number hits this (close to singularity)
  hard_stop_singularity_threshold: 18. # Stop when the condition number hits this
  cmd_out_topic:  herbie/jogging_commands
  planning_frame:  world
  low_pass_filter_coeff:  1.2.  # Larger c --> trust the filtered data more, trust the measurements less.
  pub_period:  0.005  # 1/Nominal publish rate [seconds]
  scale:
    linear:  0.0014
    rotational:  0.004
  warning_topic: jog_arm_server/warning # Publish boolean warnings to this topic